const API = "http://127.0.0.1:8000";
const $ = id => document.getElementById(id);
const fmt = (value, digits = 2) => value === null || value === undefined || Number.isNaN(Number(value)) ? "—" : Number(value).toLocaleString("en-IN", {maximumFractionDigits: digits, minimumFractionDigits: digits});
const money = value => value === null || value === undefined ? "—" : `${value < 0 ? "−" : "+"}₹${fmt(Math.abs(value), 0)}`;
const signed = value => value === null || value === undefined ? "—" : `${value < 0 ? "−" : "+"}${fmt(Math.abs(value), 1)}`;
async function api(path, options) { const response = await fetch(API + path, options); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.detail || "Request failed"); return data; }
$("connect-fyers").addEventListener("click", async () => { try { const result = await api("/fyers/login-url"); window.location.href = result.url; } catch (error) { $("alerts").innerHTML = `<li>⚠ Could not start FYERS login: ${error.message}</li>`; } });
function collectLegs() { return ["CALL BUY", "CALL SELL", "PUT SELL", "PUT BUY"].map(name => { const values = {leg: name}; document.querySelectorAll(`[data-leg="${name}"]`).forEach(input => { values[input.dataset.field] = input.type === "number" ? Number(input.value) : input.value.trim(); }); return values; }); }
$("setup-form").addEventListener("submit", async event => { event.preventDefault(); $("form-message").textContent = ""; try { await api("/manual-monitor/setup", {method: "POST", headers: {"Content-Type": "application/json"}, body: JSON.stringify({expiry: $("expiry").value, call_sl: $("call-sl").value ? Number($("call-sl").value) : null, put_sl: $("put-sl").value ? Number($("put-sl").value) : null, legs: collectLegs()})}); await refresh(); } catch (error) { $("form-message").textContent = error.message; } });
$("clear-position").addEventListener("click", async () => { await api("/manual-monitor/setup", {method: "DELETE"}); location.reload(); });
function setConnection(state) { const el = $("connection"); const connectButton = $("connect-fyers"); const label = state === "LIVE" ? "● LIVE" : state === "RECONNECTING" ? "● RECONNECTING" : "● DISCONNECTED"; el.textContent = label; el.className = `connection ${state.toLowerCase()}`; connectButton.textContent = state === "LIVE" ? "FYERS CONNECTED" : "Connect FYERS"; connectButton.disabled = state === "LIVE"; }
function renderLegs(legs) { $("legs-body").innerHTML = legs.map(leg => `<tr><td>${leg.leg}</td><td>${fmt(leg.strike, 0)}</td><td>₹${fmt(leg.entry_price)}</td><td>${leg.ltp === null ? "—" : `₹${fmt(leg.ltp)}`}</td><td>${fmt(leg.quantity, 0)}</td><td>${leg.bid == null ? "—" : `${fmt(leg.bid)} / ${fmt(leg.ask)}`}</td><td class="${leg.pnl > 0 ? "pos" : leg.pnl < 0 ? "neg" : ""}">${money(leg.pnl)}</td></tr>`).join(""); }
function renderLadder(data) { ["lower_hedge", "lower_short", "lower_breakeven", "spot", "upper_breakeven", "upper_short", "upper_hedge"].forEach(key => { const className = key === "spot" ? "spot-mark" : key.replace("_", "-"); const el = document.querySelector(`.${className}`); if (el && data[key] !== undefined) el.textContent = key === "spot" ? "●" : fmt(data[key], 0); }); }
function timeLeft(seconds) { if (seconds === undefined) return "—"; const d = Math.floor(seconds / 86400); const h = Math.floor(seconds % 86400 / 3600); const m = Math.floor(seconds % 3600 / 60); return `${d ? `${String(d).padStart(2, "0")}D ` : ""}${String(h).padStart(2, "0")}H ${String(m).padStart(2, "0")}M`; }
function render(data) { setConnection(data.connection || "DISCONNECTED"); $("last-update").textContent = `Updated ${new Date().toLocaleTimeString()}`; if (!data.configured) return; $("expiry-label").textContent = new Date(`${data.expiry}T00:00:00`).toLocaleDateString("en-IN", {weekday: "long", day: "2-digit", month: "short", year: "numeric"}); if (data.spot === undefined) { renderLegs(data.legs || []); return; } $("spot").textContent = `₹${fmt(data.spot, 1)}`; $("spot-change").textContent = `${signed(data.spot_change)} ${data.spot_change_pct == null ? "" : `(${signed(data.spot_change_pct)}%)`}`; $("time-left").textContent = timeLeft(data.seconds_to_expiry); $("total-pnl").textContent = money(data.total_pnl); $("total-pnl").className = data.total_pnl >= 0 ? "" : "neg"; $("today-pnl").textContent = money(data.total_pnl); renderLegs(data.legs); $("call-credit").textContent = `₹${fmt(data.call_credit)}`; $("put-credit").textContent = `₹${fmt(data.put_credit)}`; $("net-credit").textContent = `₹${fmt(data.net_credit)}`; $("max-profit").textContent = `₹${fmt(data.max_initial_profit, 0)}`; $("call-spread-pnl").textContent = money(data.call_spread_pnl); $("put-spread-pnl").textContent = money(data.put_spread_pnl); $("distance-put").textContent = `${fmt(Math.abs(data.distance_put_short), 0)} pts`; $("distance-call").textContent = `${fmt(Math.abs(data.distance_call_short), 0)} pts`; $("distance-lower-be").textContent = `${fmt(Math.abs(data.distance_lower_breakeven), 0)} pts`; $("distance-upper-be").textContent = `${fmt(Math.abs(data.distance_upper_breakeven), 0)} pts`; $("risk-badge").textContent = data.risk; $("risk-badge").className = `risk-badge ${data.risk.toLowerCase()}`; renderLadder(data); $("call-iv").textContent = data.call_iv == null ? "—" : `${fmt(data.call_iv, 1)}%`; $("put-iv").textContent = data.put_iv == null ? "—" : `${fmt(data.put_iv, 1)}%`; $("average-iv").textContent = data.average_short_iv == null ? "—" : `${fmt(data.average_short_iv, 1)}% (${signed(data.iv_change)})`; $("call-sl-status").textContent = data.call_sl == null ? "Not set" : `₹${fmt(data.call_sl, 0)} / ${money(data.call_spread_pnl)}`; $("put-sl-status").textContent = data.put_sl == null ? "Not set" : `₹${fmt(data.put_sl, 0)} / ${money(data.put_spread_pnl)}`; $("alerts").innerHTML = data.alerts?.length ? data.alerts.map(alert => `<li>⚠ ${alert}</li>`).join("") : `<li class="subtle">No alerts.</li>`; }
async function refresh() { try { render(await api("/manual-monitor")); } catch (error) { setConnection("RECONNECTING"); $("alerts").innerHTML = `<li>⚠ ${error.message}</li>`; } }
refresh(); setInterval(refresh, 3000);
